### ISSUE TITLE
Unable run via Go install with Go 1.19 

### ISSUE THREAD

**Issue by 56KBs** [cloudflare/cfssl#1233]
When using Go 1.19, you are unable to use cfssl if installed via `go install`

```
docker run --rm -it golang:1.19.0 /bin/bash
go install github.com/cloudflare/cfssl/cmd/cfssl@latest
root@15e509050fe5:/go# cfssl --help
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9303c6]

goroutine 1 [running]:
debug/elf.(*Section).ReadAt(0xc000124320?, {0xc0003e4c00?, 0x70?, 0x7f5f990acfff?}, 0x7f5f98ecc200?)
	<autogenerated>:1 +0x26
archive/zip.readDirectoryEnd({0xcad780, 0xc000173780}, 0x5c0)
	/usr/local/go/src/archive/zip/reader.go:526 +0xf5
archive/zip.(*Reader).init(0xc0003e21c0, {0xcad780?, 0xc000173780}, 0x5c0)
	/usr/local/go/src/archive/zip/reader.go:97 +0x5c
archive/zip.NewReader({0xcad780, 0xc000173780}, 0x5c0)
	/usr/local/go/src/archive/zip/reader.go:90 +0x5e
github.com/daaku/go%2ezipexe.zipExeReaderElf({0xcae5c0?, 0xc000014170}, 0x13a7298)
	/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.1/zipexe.go:128 +0x8b
github.com/daaku/go%2ezipexe.NewReader({0xcae5c0, 0xc000014170}, 0x0?)
	/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.1/zipexe.go:48 +0x98
github.com/daaku/go%2ezipexe.OpenCloser({0xc00003da70?, 0xc0001bbbe0?})
	/go/pkg/mod/github.com/daaku/go.zipexe@v1.0.1/zipexe.go:30 +0x57
github.com/GeertJohan/go%2erice.init.0()
	/go/pkg/mod/github.com/!geert!johan/go.rice@v1.0.2/appended.go:42 +0x65
````

This does not happen when cloning the repository & building the tools using `make`.

**Comment by tklauser** [comment]
I've noticed the same issue. It also doesn't happen when using `go install` with Go 1.18.

**Comment by batazor** [comment]
I have just installed packages via `go install ...` for go1.19 and the problem is still reproducing

```
cfssl gencert -initca ca-csr.json | cfssljson -bare ca
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x9303c6]

goroutine 1 [running]:
debug/elf.(*Section).ReadAt(0xc000146320?, {0xc00042cc00?, 0x70?, 0x7fe56626cfff?}, 0x7fe56608e600?)
	<autogenerated>:1 +0x26
archive/zip.readDirectoryEnd({0xcb17a0, 0xc0001b5800}, 0x5c0)
	/home/batazor/.gvm/gos/go1.19/src/archive/zip/reader.go:526 +0xf5
archive/zip.(*Reader).init(0xc00042a2a0, {0xcb17a0?, 0xc0001b5800}, 0x5c0)
	/home/batazor/.gvm/gos/go1.19/src/archive/zip/reader.go:97 +0x5c
```

**Comment by 56KBs** [comment]
> I have just installed packages via `go install ...` for go1.19 and the problem is still reproducing

As a release hasn't occurred yet, you'll need to install via `go install github.com/cloudflare/cfssl/cmd/cfssl@master`
