### ISSUE TITLE
CheckSignatureFrom: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by matiaskorhonen** [cloudflare/cfssl#560]
Some some certificates the revocation check panics, for example:

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xb0 pc=0x245a31]

goroutine 1 [running]:
panic(0x33d920, 0xc82000a140)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/cloudflare/cfssl/vendor/golang.org/x/crypto/ocsp.(*Response).CheckSignatureFrom(0x0, 0xc8203d6d80, 0x0, 0x0)
	$GOPATH/src/github.com/cloudflare/cfssl/vendor/golang.org/x/crypto/ocsp/ocsp.go:356 +0x31
github.com/cloudflare/cfssl/revoke.certIsRevokedOCSP(0xc820088d80, 0xc820010f00, 0x0)
	$GOPATH/src/github.com/cloudflare/cfssl/revoke/revoke.go:243 +0x273
github.com/cloudflare/cfssl/revoke.revCheck(0xc820088d80, 0x338ae71d)
	$GOPATH/src/github.com/cloudflare/cfssl/revoke/revoke.go:81 +0x48e
github.com/cloudflare/cfssl/revoke.VerifyCertificate(0xc820088d80, 0xc02f00010303)
	$GOPATH/src/github.com/cloudflare/cfssl/revoke/revoke.go:188 +0x34f
main.main()
	$GOPATH/src/gitlab.com/[REDACTED]/[REDACTED]/main.go:34 +0x3ed
exit status 2
```

This is the code I used to get that panic:

```go
package main

import (
	"crypto/tls"
	"fmt"
	"log"
	"net"
	"time"

	"github.com/cloudflare/cfssl/revoke"
)

func main() {
	hostname := "workspaces.akselworks.com"
	port := 443

	addr := fmt.Sprintf("%s:%d", hostname, port)

	dialer := net.Dialer{
		Timeout: time.Minute,
	}

	tlsConfig := tls.Config{
		InsecureSkipVerify: false,
	}

	conn, err := tls.DialWithDialer(&dialer, "tcp", addr, &tlsConfig)

	if err != nil {
		log.Fatal(err)
	}

	for _, cert := range conn.ConnectionState().PeerCertificates {
		revoked, ok := revoke.VerifyCertificate(cert)
		log.Println(revoked, ok)
	}
}
```

This is with Go 1.6 on OS X 10.11.4.

**Comment by jsha** [comment]
I'm guessing it's [these lines](https://github.com/cloudflare/cfssl/blob/master/revoke/revoke.go#L280-L282) in revoke.go:

```
	if resp.StatusCode != http.StatusOK {
		return
	}
```

Since `err` is nil in this case, the function returns nil, nil. The caller assumes that if `err` is nil, the response is non-nil.

Note: This function is a little on the long side for using named return values. Probably switching to non-named return values would be better style and make this type of bug more obvious.

**Comment by grittygrease** [comment]
@jsha take a look at this PR: https://github.com/cloudflare/cfssl/compare/nick/CheckSignatureFrom, it doesn't have tests, but it should fix this issue.

**Comment by lziest** [comment]
can this be closed?

**Comment by jsha** [comment]
Yep.
