### ISSUE TITLE
Intermittent error from CLI: fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by jimmycuadra** [cloudflare/cfssl#729]
The `cfssl` command is occasionally crashing with stderr similar to the following:

```
2017/02/13 12:33:12 [INFO] generate received request
2017/02/13 12:33:12 [INFO] received CSR
2017/02/13 12:33:12 [INFO] generating key: rsa-2048
1969/12/31 16:00:00 [INFO] encoded CSR
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x40f35b0]

goroutine 1 [running]:
runtime.throw(0x4710220, 0x2a)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:530 +0x90 fp=0xc8205e0cf8 sp=0xc8205e0ce0
runtime.sigpanic()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc8205e0d48 sp=0xc8205e0cf8
sync.(*Pool).Get(0x49271a0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/sync/pool.go:102 +0x40 fp=0xc8205e0d98 sp=0xc8205e0d48
fmt.newPrinter(0x0)
	/usr/local/Cellar/go/1.6/libexec/src/fmt/print.go:133 +0x27 fp=0xc8205e0dd8 sp=0xc8205e0d98
fmt.Sprintf(0x46dc4e0, 0x18, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6/libexec/src/fmt/print.go:202 +0x2b fp=0xc8205e0e28 sp=0xc8205e0dd8
github.com/cloudflare/cfssl/log.outputf(0x0, 0x46dc4e0, 0x18, 0x0, 0x0, 0x0)
	/private/tmp/cfssl20160407-26331-tx1g14/cfssl-1.2.0/src/github.com/cloudflare/cfssl/log/log.go:101 +0x49 fp=0xc8205e0e78 sp=0xc8205e0e28
github.com/cloudflare/cfssl/log.Debugf(0x46dc4e0, 0x18, 0x0, 0x0, 0x0)
	/private/tmp/cfssl20160407-26331-tx1g14/cfssl-1.2.0/src/github.com/cloudflare/cfssl/log/log.go:168 +0x52 fp=0xc8205e0eb0 sp=0xc8205e0e78
github.com/cloudflare/cfssl/config.(*Signing).Valid(0xc820494840, 0xc82064a1b8)
	/private/tmp/cfssl20160407-26331-tx1g14/cfssl-1.2.0/src/github.com/cloudflare/cfssl/config/config.go:441 +0x68 fp=0xc8205e0f40 sp=0xc8205e0eb0
github.com/cloudflare/cfssl/signer/universal.NewSigner(0xc820643530, 0xc820643500, 0xc820494840, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/cfssl20160407-26331-tx1g14/cfssl-1.2.0/src/github.com/cloudflare/cfssl/signer/universal/universal.go:114 +0x216 fp=0xc8205e0fe8 sp=0xc8205e0f40
github.com/cloudflare/cfssl/cli/sign.SignerFromConfigAndDB(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fff5fbff82a, 0x4b, 0x7fff5fbff87e, 0x4a, ...)
	/private/tmp/cfssl20160407-26331-tx1g14/cfssl-1.2.0/src/github.com/cloudflare/cfssl/cli/sign/sign.go:62 +0x390 fp=0xc8205e1140 sp=0xc8205e0fe8
github.com/cloudflare/cfssl/cli/sign.SignerFromConfig(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fff5fbff82a, 0x4b, 0x7fff5fbff87e, 0x4a, ...)
	/private/tmp/cfssl20160407-26331-tx1g14/cfssl-1.2.0/src/github.com/cloudflare/cfssl/cli/sign/sign.go:85 +0xd3 fp=0xc8205e1430 sp=0xc8205e1140
github.com/cloudflare/cfssl/cli/gencert.gencertMain(0xc82000a1b0, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fff5fbff82a, ...)
	/private/tmp/cfssl20160407-26331-tx1g14/cfssl-1.2.0/src/github.com/cloudflare/cfssl/cli/gencert/gencert.go:116 +0xdef fp=0xc8205e1a40 sp=0xc8205e1430
github.com/cloudflare/cfssl/cli.Start(0xc820557bc0, 0x0, 0x0)
	/private/tmp/cfssl20160407-26331-tx1g14/cfssl-1.2.0/src/github.com/cloudflare/cfssl/cli/cli.go:138 +0xb41 fp=0xc8205e1ee0 sp=0xc8205e1a40
main.main()
	/private/tmp/cfssl20160407-26331-tx1g14/cfssl-1.2.0/src/github.com/cloudflare/cfssl/cmd/cfssl/cfssl.go:76 +0x59f fp=0xc8205e1f40 sp=0xc8205e1ee0
runtime.main()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/proc.go:188 +0x2b0 fp=0xc8205e1f90 sp=0xc8205e1f40
runtime.goexit()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8205e1f98 sp=0xc8205e1f90

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6/libexec/src/runtime/asm_amd64.s:1998 +0x1
```

It happens  maybe 1 out of 30 times (totally wild guess, not measured) and does not seem to be related to any specific subcommand. Even `cfssl version` has triggered it.

I'm using the current version of cfssl bundle from Hombrew:

```
 brew info cfssl
cfssl: stable 1.2.0 (bottled), HEAD
CloudFlare's PKI toolkit
https://cfssl.org/
/usr/local/Cellar/cfssl/1.2.0_2 (4 files, 24.7M) *
  Poured from bottle on 2016-04-12 at 12:12:01
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/cfssl.rb
==> Dependencies
Build: go ✔
Required: libtool ✔
==> Caveats
`mkbundle` has been installed as `cfsslmkbundle` to avoid conflict
with Mono and other tools that ship the same executable.
```

System info:

macOS Sierra (10.12.3)
MacBook Pro (Retina, 15-inch, Mid 2014)
2.5 GHz Intel Core i7
16 GB 1600 MHz DDR3 memory

I searched for the message "fatal error: unexpected signal during runtime execution" but only found threads related to Go itself, most of which were closed without any specific resolution. Is it possible there is some problem with cfssl compiled with an older version of Go on the latest macOS? Note that Homebrew installs a precompiled binary, and does not use the version of Go installed on my own system.

**Comment by jimmycuadra** [comment]
I uninstalled and reinstalled via Homebrew and now can't reproduce this. I guess it was only an issue with a binary built in an older environment.
